# -*- coding: utf-8 -*-
"""Agentic_AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10WMyPfdQPZCV7baEXmfCANzzUh-FfiqM
"""

from google.colab import files
uploaded = files.upload()

import os

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = list(uploaded.keys())[0]

!pip install google-cloud-vision

from google.cloud import vision
import io

client = vision.ImageAnnotatorClient()

def extract_text(image_path):
    with io.open(image_path, 'rb') as image_file:
        content = image_file.read()

    image = vision.Image(content=content)
    response = client.text_detection(image=image)

    texts = response.text_annotations

    if texts:
        return texts[0].description
    else:
        return ""

!pip install langchain-groq

from google.colab import files
import re

from google.colab import userdata
GROQ_API_KEY = userdata.get("GROQ_API_KEY")

from langchain_groq import ChatGroq

model = ChatGroq(
    model="openai/gpt-oss-20b",
    api_key=GROQ_API_KEY
)

print("Groq Connected ✅")

print("===== ENTER YOUR DETAILS =====")
total_income = int(input("Enter your monthly income: "))

total_expense = 0
essential_spending = 0
non_essential_spending = 0

uploaded = files.upload()

def extract_text(image_file):
    img = Image.open(image_file)
    text = pytesseract.image_to_string(img)
    return text

def extract_amount(text):
    import re

    # Look for ₹ or Rs patterns
    matches = re.findall(r'(?:₹|rs\.?|inr)?\s?([\d,]+)', text.lower())

    amounts = []
    for m in matches:
        try:
            val = int(m.replace(',', ''))
            if val > 50:   # ignore small numbers like time
                amounts.append(val)
        except:
            pass

    if amounts:
        return max(amounts)   # take biggest → usually correct
    else:
        return 0

def classify_transaction(text):
    prompt = f"""
    You are a strict financial classifier.

    Classify the transaction clearly.

    Rules:
    - Food delivery (Swiggy, Zomato) → Non-Essential
    - Movies, subscriptions → Non-Essential
    - Rent, groceries, education → Essential

    Return ONLY this format (no extra text):

    Type: Expense
    Nature: Essential OR Non-Essential
    Category: <one word>

    Text: {text}
    """

    response = model.invoke(prompt)
    return response.content.lower()

def clean_text(text):
    lines = text.split('\n')

    useful_lines = []
    keywords = ["paid", "amount", "₹", "rs", "zomato", "swiggy", "market", "fuel", "rent"]

    for line in lines:
        line_lower = line.lower()
        if any(k in line_lower for k in keywords):
            useful_lines.append(line)

    return " ".join(useful_lines)
for file in uploaded.keys():
    print("\nProcessing:", file)

    text = extract_text(file)

    print("RAW TEXT:", text)

    # 👇 USE clean_text HERE
    text = clean_text(text)

    print("CLEAN TEXT:", text)

    amount = extract_amount(text)
    print("Detected Amount:", amount)

    result = classify_transaction(text)
    print("Groq Output:\n", result)

    total_expense += amount

    # Correct logic
    if "non-essential" in result:
        non_essential_spending += amount
    elif "essential" in result:
        essential_spending += amount

savings = total_income - total_expense

if total_income > 0:
    savings_percent = (savings / total_income) * 100
else:
    savings_percent = 0

print("\n===== FINAL SUMMARY =====")

print("Total Income:", total_income)
print("Total Expense:", total_expense)
print("Essential Spending:", essential_spending)
print("Non-Essential Spending:", non_essential_spending)
print("Savings:", savings)
print("Savings %:", savings_percent)

print("\n===== FINANCIAL ADVICE =====")

if savings_percent < 25:
    if non_essential_spending > 0:
        print("⚠️ Savings < 25%")
        print("👉 Reduce non-essential expenses.")
    else:
        print("⚠️ Low savings even without non-essential spending.")
        print("👉 Optimize essential expenses.")
else:
    print("✅ Good savings habit!")

if non_essential_spending == 0:
    print("💡 No non-essential spending.")
    print("👉 You can invest more money.")